version : '3.8'
services: 
  dev-db:
    image: postgres:16
    ports:
      - '3000:3002'
    environment:
      POSTGRES_PASSWORD : '1234'
      POSTGRES_USER : 'nest'
#     networks:
#       - test
# networks:
#   test: