services: 
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD : 1234
      POSTGRES_USER : user
      POSTGRES_DB : nest
    networks:
      - test
networks:
  test: